// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI textbook
  textbookSidebar: [
    {
      type: 'category',
      label: 'Module 1: Fundamentals of Physical AI',
      items: [
        'module-1/index',
        'module-1/introduction-to-physical-ai',
        'module-1/ros2-fundamentals',
        'module-1/sensor-integration-basics',
        'module-1/actuator-control-systems',
        'module-1/embodied-intelligence-concepts',
        'module-1/module-1-capstone'
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        // Placeholder for future content
        {
          type: 'autogenerated',
          dirName: 'module-2',
        }
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3/index',
        'module-3/3.1-nvidia-isaac-sim',
        'module-3/3.2-isaac-ros-vslam',
        'module-3/3.3-navigation-nav2'
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4/index',
        'module-4/4.1-voice-to-action-whisper',
        'module-4/4.2-cognitive-planning-llm',
        'module-4/4.3-capstone-autonomous-humanoid'
      ],
    },
  ],

  // Original autogenerated sidebar
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
