openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API contract for the RAG Chatbot backend integration
  version: 1.0.0
servers:
  - url: https://your-backend-domain.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

paths:
  /api/agent/query:
    post:
      summary: Process a user query against the RAG system
      description: Sends a user query to the backend RAG system and returns an AI-generated response
      operationId: processQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response with AI-generated answer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Bad request - invalid query format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []

  /health:
    get:
      summary: Check backend service health
      description: Returns the health status of the backend service
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Optional API key for authentication

  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's query text
          example: "What is the definition of embodied intelligence?"
          maxLength: 2000
        context:
          type: object
          description: Additional context for the query
          properties:
            selected_text:
              type: string
              description: Text selected by user on the page
              example: "Embodied intelligence refers to..."
              maxLength: 1000
            page_url:
              type: string
              description: URL of the current page
              example: "https://example.com/docs/embodied-ai"
            page_title:
              type: string
              description: Title of the current page
              example: "Embodied AI Concepts"
        parameters:
          type: object
          description: Additional parameters for query processing
          properties:
            temperature:
              type: number
              description: AI temperature setting (0-1)
              example: 0.7
              minimum: 0
              maximum: 1
            max_tokens:
              type: number
              description: Maximum tokens to generate
              example: 500
              minimum: 1
              maximum: 2000

    QueryResponse:
      type: object
      required:
        - answer
      properties:
        answer:
          type: string
          description: The AI-generated answer to the query
          example: "Embodied intelligence refers to the..."
        sources:
          type: array
          description: Sources referenced in the answer
          items:
            type: string
          example: ["source1.md", "source2.md"]
        confidence:
          type: number
          description: Confidence score of the response (0-1)
          example: 0.85
          minimum: 0
          maximum: 1
        retrieved_context:
          type: array
          description: Context retrieved from the knowledge base
          items:
            type: string
          example: ["Context about embodied intelligence...", "Definition from textbook..."]
        followup_questions:
          type: array
          description: Suggested follow-up questions
          items:
            type: string
          example: ["What are the key components?", "How does it differ from traditional AI?"]
        timestamp:
          type: string
          description: When the response was generated
          format: date-time
          example: "2023-12-22T10:00:00Z"

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Health status of the service
          enum: [healthy, unhealthy]
          example: "healthy"
        version:
          type: string
          description: Version of the service
          example: "1.0.0"
        timestamp:
          type: string
          format: date-time
          description: When the health check was performed
          example: "2023-12-22T10:00:00Z"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid query format"
        code:
          type: string
          description: Error code
          example: "INVALID_QUERY"
        details:
          type: object
          description: Additional error details
          example: {"field": "query", "reason": "must not be empty"}